"""
Pydantic models for ML model package data structures.

This module defines the data models for storing and transferring
trained machine learning models and their associated metadata.
"""

from pydantic import BaseModel, Field
from typing import Optional, Any, List

class MLModelPackage(BaseModel):
    """
    Complete ML model package retrieved from the database.

    This model includes all fields including the package_id from MongoDB.
    """
    package_id: str = Field(..., description="MongoDB document ID", alias="_id")
    package_label: str = Field(..., description="ML model package label")
    model: str = Field(..., description="Trained ML model (stored as base64 encoded string)")
    model_features: List[str] = Field(..., description="List of features the model expects")
    model_scores: dict[str, Any] = Field(..., description="Dict of model scores")
    dataset: List[dict] = Field(..., description="Dataset the model was trained on")
    model_target: str = Field(..., description="Target column of the model")
    date_trained: str = Field(..., description="Date the model was trained")

class CreateMLModelPackageRequest(BaseModel):
    """
    Request model for creating a new ML model package.

    This model is used when creating or updating model packages in the database.
    It excludes the package_id field which is generated by MongoDB.
    """
    package_label: str = Field(..., description="ML model package label")
    model: str = Field(..., description="Trained ML model (stored as base64 encoded string)")
    model_features: List[str] = Field(..., description="List of features the model expects")
    model_scores: dict[str, Any] = Field(..., description="Dict of model scores")
    dataset: List[dict] = Field(..., description="Dataset the model was trained on")
    model_target: str = Field(..., description="Target column of the model")
    date_trained: str = Field(..., description="Date the model was trained")